name: Juice Shop DAST ZAP Scan

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

jobs:
 # zap scan:
  #  runs-on: ubuntu-latest
   # name: dast zap scan juice shop
    #steps:
    #- name: Checkout code
     # uses: actions/checkout@v2

    #- name: the actual dast zap scan
  pass-secret-to-action:
    runs-on: ubuntu-latest
    steps:
      - name: Use a repo or org secret from the calling workflow.
        run: echo ${{ secrets.CALLING_WORKFLOW_SECRET }}
